/*
  Warnings:

  - You are about to alter the column `ORDER_NUM` on the `open_position` table. The data in that column could be lost. The data in that column will be cast from `Int` to `Decimal(5,2)`.

*/
-- AlterTable
ALTER TABLE `open_position` MODIFY `ORDER_NUM` DECIMAL(5, 2) NULL DEFAULT 0.00,
    MODIFY `NEW_DETAIL_GROUP` VARCHAR(100) NOT NULL,
    MODIFY `USD` DECIMAL(15, 2) NULL DEFAULT 0.00,
    MODIFY `EUR` DECIMAL(15, 2) NULL DEFAULT 0.00,
    MODIFY `CHF` DECIMAL(15, 2) NULL DEFAULT 0.00,
    MODIFY `GBP` DECIMAL(15, 2) NULL DEFAULT 0.00,
    MODIFY `JPY` DECIMAL(15, 2) NULL DEFAULT 0.00,
    MODIFY `DJF` DECIMAL(15, 2) NULL DEFAULT 0.00,
    MODIFY `KES` DECIMAL(15, 2) NULL DEFAULT 0.00,
    MODIFY `INR` DECIMAL(15, 2) NULL DEFAULT 0.00,
    MODIFY `DKK` DECIMAL(15, 2) NULL DEFAULT 0.00,
    MODIFY `SEK` DECIMAL(15, 2) NULL DEFAULT 0.00,
    MODIFY `SAR` DECIMAL(15, 2) NULL DEFAULT 0.00,
    MODIFY `CAD` DECIMAL(15, 2) NULL DEFAULT 0.00,
    MODIFY `AED` DECIMAL(15, 2) NULL DEFAULT 0.00,
    MODIFY `AUD` DECIMAL(15, 2) NULL DEFAULT 0.00,
    MODIFY `CNY` DECIMAL(15, 2) NULL DEFAULT 0.00,
    MODIFY `NOK` DECIMAL(15, 2) NULL DEFAULT 0.00,
    MODIFY `KWD` DECIMAL(15, 2) NULL DEFAULT 0.00,
    MODIFY `SSP` DECIMAL(15, 2) NULL DEFAULT 0.00,
    MODIFY `OVERALL_EXPOSURE` DECIMAL(20, 2) NULL DEFAULT 0.00;
