-- CreateTable
CREATE TABLE `OPEN_POSITION` (
    `id` VARCHAR(36) NOT NULL,
    `BUSINESS_DATE` DATE NOT NULL,
    `ORDER_NUM` INTEGER NOT NULL,
    `NEW_DETAIL_GROUP` VARCHAR(50) NOT NULL,
    `USD` DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    `EUR` DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    `CHF` DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    `GBP` DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    `JPY` DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    `DJF` DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    `KES` DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    `INR` DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    `DKK` DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    `SEK` DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    `SAR` DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    `CAD` DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    `AED` DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    `AUD` DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    `CNY` DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    `NOK` DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    `KWD` DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    `SSP` DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    `OVERALL_EXPOSURE` DECIMAL(20, 2) NOT NULL DEFAULT 0.00,
    `curr` INTEGER NOT NULL DEFAULT 0,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
